site_name: AIDIY Wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - attr_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/mathjax_config.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.css
nav:
  - Home: index.md
  - 数学基础: 
    - 矩阵满秩分解: Mathematical_Foundation/Linear_Algebra/Matrix_Decomposition/Full_Rank_Decomposition.md
    - 矩阵求导: Mathematical_Foundation/Linear_Algebra/Matrix_Calculation.md
    - 流形假设: Mathematical_Foundation/Manifold/Manifold_hypothesis.md

  - Machine Learning:
    - CNN: ML_Pages/CNN.md
    - MLP: ML_Pages/MLP.md
    - RNN: ML_Pages/RNN.md
    - VAE: ML_Pages/VAE.md
  - LLM:
    - Transformer数学架构: LLM_Pages/Math_Architecture.md
    - 位置编码: LLM_Pages/Position_Embedding.md
    - 预训练阶段: LLM_Pages/Pre-Train.md
    - SFT阶段: LLM_Pages/SFT.md
    - 后训练阶段: LLM_Pages/Post-Train.md
  - 工程实践: 
    - LlamaFactory入门: Engineering_Pages/LlamaFactory.md
    - vllm部署模型: Engineering_Pages/VLLM.md
    - 全量微调: Engineering_Pages/Full_SFT_LlamaFactory.md
  - RL:
    - RL基础概念: RL_Pages/RL.md
    - 蒙特卡洛树搜索: RL_Pages/Monte_Carlos.md
  - LLM_RLHF阶段: 
    - PPO: RLHF_Pages/PPO.md
    - DPO: RLHF_Pages/DPO.md
    - SimPO: RLHF_Pages/SimPO.md
  - StableDiffusion: stablediffusion.md




extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Joining-AI/LLM_Interview_Prepare
      text: Star on GitHub
